"use client";
import React, { useState, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { products, Product } from "@/data/product";
import Navbar from "@/components/Navbar";
import { ArrowLeft, ShoppingCart, Heart, Share2, Tag } from "lucide-react";

const DetailProductPage = () => {
  const searchParams = useSearchParams();
  const productId = searchParams.get('id');
  const [product, setProduct] = useState<Product | null>(null);
  const [selectedImageIndex, setSelectedImageIndex] = useState(0);
  const [selectedLicenseType, setSelectedLicenseType] = useState<"personal" | "commercial" | "enterprise">("personal");
  const [quantity, setQuantity] = useState(1);
  const [isAddingToCart, setIsAddingToCart] = useState(false);

  useEffect(() => {
    if (productId) {
      const foundProduct = products.find(p => p.id === productId);
      setProduct(foundProduct || null);
      if (foundProduct) {
        setSelectedLicenseType(foundProduct.jenisLisensi);
      }
    }
  }, [productId]);

  const addToCart = () => {
    if (!product) return;
    
    setIsAddingToCart(true);
    
    // Get existing cart
    const existingCart = localStorage.getItem('lumbungRupa_cart');
    let cartItems = [];
    
    if (existingCart) {
      try {
        cartItems = JSON.parse(existingCart);
      } catch (error) {
        console.error('Error parsing cart:', error);
        cartItems = [];
      }
    }
    
    // Check if item already exists in cart
    const existingItemIndex = cartItems.findIndex(
      (item: any) => item.productId === product.id && item.licenseType === selectedLicenseType
    );
    
    if (existingItemIndex !== -1) {
      // Update quantity if item exists
      cartItems[existingItemIndex].quantity += quantity;
    } else {
      // Add new item
      cartItems.push({
        productId: product.id,
        quantity: quantity,
        licenseType: selectedLicenseType,
        addedAt: new Date().toISOString()
      });
    }
    
    // Save to localStorage
    localStorage.setItem('lumbungRupa_cart', JSON.stringify(cartItems));
    
    // Dispatch custom event to update cart count in navbar
    window.dispatchEvent(new Event('cartUpdated'));
    
    setTimeout(() => {
      setIsAddingToCart(false);
      // Optional: Show success message or redirect to cart
      alert(`${product.title} berhasil ditambahkan ke keranjang!`);
    }, 500);
  };

  const getLicenseMultiplier = (licenseType: string) => {
    switch (licenseType) {
      case 'personal': return 1;
      case 'commercial': return 2;
      case 'enterprise': return 3;
      default: return 1;
    }
  };

  const getCurrentPrice = () => {
    if (!product) return 0;
    return product.price * getLicenseMultiplier(selectedLicenseType);
  };

  if (!product) {
    return (
      <div>
        <Navbar />
        <div className="container mx-auto px-4 py-8 text-center">
          <p className="text-xl text-gray-600">Produk tidak ditemukan</p>
          <Link href="/product" className="text-primary hover:underline mt-4 inline-block">
            Kembali ke katalog
          </Link>
        </div>
      </div>
    );
  }

  const formatPrice = (price: number) => {
    return new Intl.NumberFormat('id-ID', {
      style: 'currency',
      currency: 'IDR',
      minimumFractionDigits: 0,
    }).format(price);
  };

  const relatedProducts = products
    .filter(p => p.kategori === product.kategori && p.id !== product.id)
    .slice(0, 4);

  return (
    <div>
      <Navbar />
      <div className="container mx-auto px-4 py-8">
        {/* Back Button */}
        <div className="mb-6">
          <Link
            href="/product"
            className="inline-flex items-center text-gray-600 hover:text-primary transition-colors"
          >
            <ArrowLeft size={20} className="mr-2" />
            Kembali ke Katalog
          </Link>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          {/* Image Gallery */}
          <div>
            <div className="aspect-square relative overflow-hidden rounded-2xl mb-4">
              <Image
                src={product.imageUrl[selectedImageIndex] || product.thumbnail}
                alt={product.title}
                fill
                className="object-cover"
              />
              {product.isGenerative && (
                <div className="absolute top-4 right-4">
                  <span className="px-3 py-2 bg-primary text-white text-sm rounded-full">
                    Generated by AI
                  </span>
                </div>
              )}
            </div>
            
            {/* Thumbnail Gallery */}
            {product.imageUrl.length > 1 && (
              <div className="flex gap-3 overflow-x-auto">
                {product.imageUrl.map((url, index) => (
                  <button
                    key={index}
                    onClick={() => setSelectedImageIndex(index)}
                    className={`flex-shrink-0 w-20 h-20 rounded-lg overflow-hidden border-2 ${
                      selectedImageIndex === index
                        ? "border-primary"
                        : "border-gray-200"
                    }`}
                  >
                    <Image
                      src={url}
                      alt={`${product.title} ${index + 1}`}
                      width={80}
                      height={80}
                      className="object-cover w-full h-full"
                    />
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Product Info */}
          <div>
            <div className="mb-4">
              <span className="px-3 py-1 bg-primary/10 text-primary text-sm rounded-full">
                {product.kategori}
              </span>
            </div>

            <h1 className="text-3xl font-normal text-gray-900 mb-4">
              {product.title}
            </h1>

            <p className="text-gray-600 mb-6 leading-relaxed">
              {product.description}
            </p>

            {/* Creator Info */}
            <div className="mb-6">
              <p className="text-sm text-gray-500 mb-1">Dibuat oleh:</p>
              <p className="font-medium text-gray-900">{product.creator}</p>
            </div>

            {/* License Type Selector */}
            <div className="mb-6">
              <p className="text-sm font-medium text-gray-700 mb-3">Pilih Jenis Lisensi:</p>
              <div className="space-y-2">
                <label className="flex items-center p-3 border border-gray-300 rounded-xl cursor-pointer hover:bg-gray-50">
                  <input
                    type="radio"
                    name="licenseType"
                    value="personal"
                    checked={selectedLicenseType === "personal"}
                    onChange={(e) => setSelectedLicenseType(e.target.value as "personal")}
                    className="mr-3"
                  />
                  <div className="flex-1">
                    <div className="font-medium">Personal (1x)</div>
                    <div className="text-sm text-gray-600">Untuk penggunaan pribadi</div>
                  </div>
                  <div className="text-primary font-medium">
                    {formatPrice(product.price)}
                  </div>
                </label>
                <label className="flex items-center p-3 border border-gray-300 rounded-xl cursor-pointer hover:bg-gray-50">
                  <input
                    type="radio"
                    name="licenseType"
                    value="commercial"
                    checked={selectedLicenseType === "commercial"}
                    onChange={(e) => setSelectedLicenseType(e.target.value as "commercial")}
                    className="mr-3"
                  />
                  <div className="flex-1">
                    <div className="font-medium">Commercial (2x)</div>
                    <div className="text-sm text-gray-600">Untuk penggunaan komersial</div>
                  </div>
                  <div className="text-primary font-medium">
                    {formatPrice(product.price * 2)}
                  </div>
                </label>
                <label className="flex items-center p-3 border border-gray-300 rounded-xl cursor-pointer hover:bg-gray-50">
                  <input
                    type="radio"
                    name="licenseType"
                    value="enterprise"
                    checked={selectedLicenseType === "enterprise"}
                    onChange={(e) => setSelectedLicenseType(e.target.value as "enterprise")}
                    className="mr-3"
                  />
                  <div className="flex-1">
                    <div className="font-medium">Enterprise (3x)</div>
                    <div className="text-sm text-gray-600">Untuk penggunaan enterprise</div>
                  </div>
                  <div className="text-primary font-medium">
                    {formatPrice(product.price * 3)}
                  </div>
                </label>
              </div>
            </div>

            {/* Quantity Selector */}
            <div className="mb-6">
              <p className="text-sm font-medium text-gray-700 mb-3">Kuantitas:</p>
              <div className="flex items-center gap-3">
                <button
                  onClick={() => setQuantity(Math.max(1, quantity - 1))}
                  className="w-10 h-10 rounded-full border border-gray-300 flex items-center justify-center hover:bg-gray-50"
                >
                  -
                </button>
                <span className="w-12 text-center font-medium">{quantity}</span>
                <button
                  onClick={() => setQuantity(quantity + 1)}
                  className="w-10 h-10 rounded-full border border-gray-300 flex items-center justify-center hover:bg-gray-50"
                >
                  +
                </button>
              </div>
            </div>

            {/* Metadata */}
            <div className="grid grid-cols-1 gap-4 mb-6">
              {product.resolution && (
                <div>
                  <p className="text-sm text-gray-500 mb-1">Resolusi:</p>
                  <p className="font-medium text-gray-900">{product.resolution}</p>
                </div>
              )}
            </div>

            {/* Tags */}
            <div className="mb-6">
              <p className="text-sm text-gray-500 mb-2 flex items-center">
                <Tag size={16} className="mr-1" />
                Tags:
              </p>
              <div className="flex flex-wrap gap-2">
                {product.tags.map((tag, index) => (
                  <span
                    key={index}
                    className="px-3 py-1 bg-gray-100 text-gray-700 text-sm rounded-full"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            </div>

            {/* Price and Actions */}
            <div className="border-t pt-6">
              <div className="flex items-center justify-between mb-6">
                <div>
                  <p className="text-sm text-gray-500 mb-1">Total Harga:</p>
                  <p className="text-3xl font-medium text-primary">
                    {formatPrice(getCurrentPrice() * quantity)}
                  </p>
                </div>
              </div>

              <div className="flex gap-3 mb-4">
                <button 
                  onClick={addToCart}
                  disabled={isAddingToCart}
                  className="flex-1 bg-primary text-white py-4 px-6 rounded-full font-medium hover:bg-primary/90 transition-colors flex items-center justify-center gap-2 disabled:opacity-50"
                >
                  <ShoppingCart size={20} />
                  {isAddingToCart ? "Menambahkan..." : "Beli Lisensi"}
                </button>
                <button className="p-4 border border-gray-300 rounded-full hover:bg-gray-50 transition-colors">
                  <Heart size={20} />
                </button>
                <button className="p-4 border border-gray-300 rounded-full hover:bg-gray-50 transition-colors">
                  <Share2 size={20} />
                </button>
              </div>

              <div className="text-center mb-4">
                <Link
                  href="/cart"
                  className="text-primary hover:underline text-sm"
                >
                  Lihat Keranjang
                </Link>
              </div>

              <p className="text-xs text-gray-500 text-center">
                Dengan membeli, Anda menyetujui syarat dan ketentuan lisensi
              </p>
            </div>
          </div>
        </div>

        {/* Related Products */}
        {relatedProducts.length > 0 && (
          <div className="mt-16">
            <h2 className="text-2xl font-normal text-gray-900 mb-8">
              Aset Serupa dari Kategori {product.kategori}
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {relatedProducts.map((relatedProduct) => (
                <Link
                  key={relatedProduct.id}
                  href={`/detail-product?id=${relatedProduct.id}`}
                  className="group border border-gray-200 rounded-2xl overflow-hidden hover:shadow-lg transition-shadow"
                >
                  <div className="aspect-square relative overflow-hidden">
                    <Image
                      src={relatedProduct.thumbnail}
                      alt={relatedProduct.title}
                      fill
                      className="object-cover group-hover:scale-105 transition-transform duration-300"
                    />
                  </div>
                  <div className="p-4">
                    <h3 className="font-normal text-gray-900 mb-2 group-hover:text-primary transition-colors">
                      {relatedProduct.title}
                    </h3>
                    <p className="text-sm text-primary font-medium">
                      {formatPrice(relatedProduct.price)}
                    </p>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default DetailProductPage;